### PR TITLE
fix: mentions not working

### LINKED ISSUE #425: Fix mentions not sent

### PR DESCRIPTION
**Pull request by spaenleh**
This PR fixes the mentions not working by using the latest branch from chatbox

closes #425

### CODE REVIEW

File: src/components/item/settings/ClearChatButton.js [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+            variant="outlined"
+            onClick={() => {
+              setOpenConfirmation(false);
+              handleClearChat();
+            }}
+          >
+            {t(CHATBOX.CLEAR_ALL_CHAT)}
+          </Button>
+        </DialogActions>
+      </Dialog>
```
Comment (spaenleh) [inline src/components/item/settings/ClearChatButton.js:103]: @swouf this is an example of how you can use the Dialog Component in material-ui as discussed in the sticky-notes-app. Thought it could be interesting 😊

File: src/components/item/settings/DownloadChatButton.js [hunk 2]
```diff
@@ -0,0 +1,103 @@
...
+  },
+});
+
+// todo: convert this into a backend call
+const DownloadChatButton = ({ chatId, variant }) => {
+  const [filename, setFilename] = useState('');
+  const { t } = useTranslation();
+  const classes = useStyles();
+
+  const { data: exportedChat, isLoading } = hooks.useExportItemChat(chatId);
```
Comment (pyphilia) [inline src/components/item/settings/DownloadChatButton.js:33]: The problem using a hook is that you would always export the chat even tho the user didn't click on the button.

File: src/components/item/settings/ItemSettings.js [hunk 3]
```diff
@@ -36,7 +37,11 @@ const useStyles = makeStyles((theme) => ({
   },
   collapseTooltip: {
     color: 'lightgrey',
-    marginBottom: -theme.spacing(0.5),
+    // marginBottom: -theme.spacing(0.5),
```
Comment (pyphilia) [inline src/components/item/settings/ItemSettings.js:40]: Remove.

**Review by pyphilia — CHANGES_REQUESTED** [review]

**Review by pyphilia — APPROVED** [review]
