### PR TITLE
fix: case-insensitive autocomplete comparison

### LINKED ISSUE #528: Fix case-insensitive autocomplete
The autocomplete now works on the name of the apps but it is case-sensitive.
We should make it case-insensitive.

### PR DESCRIPTION
**Pull request by spaenleh**
This PR fixes dumb issues created in #514:
- comparison of the strings should be made in lowercase
- resizable setting should be show when `ItemType` is `app`

closes #528

### CODE REVIEW

File: src/components/item/settings/ItemSettings.tsx [hunk 1]
```diff
@@ -183,8 +183,7 @@ const ItemSettings: FC<Props> = ({ item }) => {
         {renderPinSetting()}
         {renderChatSetting()}
         {renderCollapseSetting()}
-        {/* todo: change itemType to app */}
-        {item.type === ItemType.FOLDER && renderResizeSetting()}
+        {item.type === ItemType.APP && renderResizeSetting()}
```
Comment (dialexo) [inline src/components/item/settings/ItemSettings.tsx:186]: Quick question, do you know why this was set to folder?

**Review by dialexo — APPROVED** [review]
LGTM 🏋️

File: src/components/item/settings/ItemSettings.tsx (hunk 1 above)
Comment (spaenleh) [reply src/components/item/settings/ItemSettings.tsx:186]: Left over by me from testing in #514 ... 😅
